export const savingsCircleAbi = [
  {
    type: 'function',
    name: 'nextCircleId',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'createCircle',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'token', type: 'address' },
      { name: 'contributionAmount', type: 'uint96' },
      { name: 'roundDuration', type: 'uint64' },
      { name: 'maxMembers', type: 'uint32' },
      { name: 'name', type: 'string' },
    ],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'joinCircle',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'circleId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'startCircle',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'circleId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'contribute',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'circleId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'forceAdvance',
    stateMutability: 'nonpayable',
    inputs: [{ name: 'circleId', type: 'uint256' }],
    outputs: [],
  },
  {
    type: 'function',
    name: 'getCircle',
    stateMutability: 'view',
    inputs: [{ name: 'circleId', type: 'uint256' }],
    outputs: [
      {
        type: 'tuple',
        components: [
          { name: 'creator', type: 'address' },
          { name: 'token', type: 'address' },
          { name: 'contributionAmount', type: 'uint256' },
          { name: 'roundDuration', type: 'uint256' },
          { name: 'startTime', type: 'uint256' },
          { name: 'maxMembers', type: 'uint256' },
          { name: 'currentRound', type: 'uint256' },
          { name: 'started', type: 'bool' },
          { name: 'completed', type: 'bool' },
          { name: 'name', type: 'string' },
          { name: 'memberCount', type: 'uint256' },
        ],
      },
    ],
  },
  {
    type: 'function',
    name: 'getMembers',
    stateMutability: 'view',
    inputs: [{ name: 'circleId', type: 'uint256' }],
    outputs: [{ type: 'address[]' }],
  },
  {
    type: 'function',
    name: 'isMember',
    stateMutability: 'view',
    inputs: [
      { name: 'circleId', type: 'uint256' },
      { name: 'user', type: 'address' },
    ],
    outputs: [{ type: 'bool' }],
  },
  {
    type: 'function',
    name: 'hasContributed',
    stateMutability: 'view',
    inputs: [
      { name: 'circleId', type: 'uint256' },
      { name: 'round', type: 'uint256' },
      { name: 'user', type: 'address' },
    ],
    outputs: [{ type: 'bool' }],
  },
  {
    type: 'function',
    name: 'currentRecipient',
    stateMutability: 'view',
    inputs: [{ name: 'circleId', type: 'uint256' }],
    outputs: [{ type: 'address' }],
  },
  {
    type: 'function',
    name: 'roundDeadline',
    stateMutability: 'view',
    inputs: [{ name: 'circleId', type: 'uint256' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'protocolFeeBps',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'protocolFeeRecipient',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'address' }],
  },
] as const;

export const erc20Abi = [
  {
    type: 'function',
    name: 'balanceOf',
    stateMutability: 'view',
    inputs: [{ name: 'a', type: 'address' }],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'allowance',
    stateMutability: 'view',
    inputs: [
      { name: 'owner', type: 'address' },
      { name: 'spender', type: 'address' },
    ],
    outputs: [{ type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'approve',
    stateMutability: 'nonpayable',
    inputs: [
      { name: 'spender', type: 'address' },
      { name: 'amount', type: 'uint256' },
    ],
    outputs: [{ type: 'bool' }],
  },
  {
    type: 'function',
    name: 'symbol',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'string' }],
  },
  {
    type: 'function',
    name: 'decimals',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ type: 'uint8' }],
  },
] as const;
